### ISSUE TITLE
Add BEAM water quality processing modules

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/processing_gpf#12]
Upon request by GW-A Toolbox user K:
- coastcolour-processing-1.8.3
- CoastColour L1P (including IdePix processor)
- CoastColour L2R
- CoastColour L2W
- MPH
- beam-wew-water-2.2
- Beam-owt-classification
- Binning (already included)

**Comment by j08lue** [comment]
Coastcolour and dependencies:

![image](https://cloud.githubusercontent.com/assets/3404817/17811809/a6f14b2c-6624-11e6-8df1-f168516bfbdc.png)

**Comment by j08lue** [comment]
Thanks for your helpful comments today, @radosuav .

I know where to get the necessary `.jar` files, but do you happen to know where to get the `.jar.uninstall` files from that we have in the WOIS package (or if they are necessary at all)?

![image](https://cloud.githubusercontent.com/assets/3404817/17813294/192a77bc-662b-11e6-90f1-2bb85ee6eb6e.png)

**Comment by radosuav** [comment]
I don't remember all the details but I think that the uninstall files are there to remove any previous version of a module when BEAM is restarted. For example, when beam-avhrr-reader is updated from version 5.0.1 to 5.0.2 within BEAM then both beam-avhrr-reader-5.0.1.jar and beam-avhrr-reader-5.0.2.jar will be in the modules folder, as well as beam-avhrr-reader-5.0.1.jar.uninstall. When BEAM is restarted the uninstall will remove beam-avhrr-reader-5.0.1.jar and itself.

So you can get the uninstall files by updating all the modules within BEAM and copying *.uninstall before restarting BEAM. If you are installing a new module (e.g. coastcolour) then I guess .uninstall won't exist.

**Comment by j08lue** [comment]
I added most of the algorithms with commit https://github.com/DHI-GRAS/processing_gpf/commit/dc4d447502f5d71a88395d496f2fb86d1a778027 but these are yet **untested**. I will get back on whether they work as intended as soon as possible.

@radosuav could you help me adding the **Level-3 Binning** algorithm? I have a [stump in the binning branch](https://github.com/DHI-GRAS/processing_gpf/blob/binning/beam_description/Binning.txt), but I am stuck with the following questions:

### Adding intermediate source bands (variables) and aggregators

This is about generating nested XML. Please see an example in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/3404817/18167568/92babb5c-7051-11e6-867a-4689d9a71558.png)

and the resulting XML is:

``` XML
<parameters>
 <sourceProductPaths>path\to\some\sample\file</sourceProductPaths>
    <timeFilterMethod>NONE</timeFilterMethod>
    <numRows>2160</numRows>
    <superSampling>1</superSampling>
    <maskExpr>true</maskExpr>
    <variables>
        <variable>
            <name>variable_0</name>
            <expr>band_1 * 1.0</expr>
        </variable>
    </variables>
    <aggregators>
        <aggregator>
            <type>AVG</type>
            <varName>band_1</varName>
            <weightCoeff>0.0</weightCoeff>
            <outputCounts>true</outputCounts>
            <outputSums>true</outputSums>
        </aggregator>
        <aggregator>
            <type>MIN_MAX</type>
            <varName>band_1</varName>
            <targetName/>
        </aggregator>
        <aggregator>
            <type>ON_MAX_SET</type>
            <onMaxVarName>band_1</onMaxVarName>
            <targetName/>
            <setVarNames>variable_0</setVarNames>
        </aggregator>
        <aggregator>
            <type>PERCENTILE</type>
            <varName>band_1</varName>
            <targetName/>
            <percentage>10</percentage>
        </aggregator>
    </aggregators>
    <outputFile>level-3.dim</outputFile>
    <metadataAggregatorName>NAME</metadataAggregatorName>
</parameters>
```

I can see that QGIS on `ParameterNumber` provides a possibility for expression-based input. Is that it? But that probably does not generate the right XML, does it?

### Multiple source files

Another question is how to generate a list of several input files. I adapted this method:

```
ParameterRaster|1ProductSet-Reader>sourceProductPaths|Input product 1|False|False
ParameterRaster|2ProductSet-Reader>sourceProductPaths|Input product 2|True|False
ParameterRaster|3ProductSet-Reader>sourceProductPaths|Input product 3|True|False
ParameterRaster|4ProductSet-Reader>sourceProductPaths|Input product 4|True|False
```

or is there a better way?

**Comment by radosuav** [comment]
Yes this one is hard and it's probably not possible to make it look pretty in Processing right now unless a full custom parameters panel is created. See for example "Refractor fields" and "Field calculator" algorithms and https://github.com/DHI-GRAS/QGIS/tree/master/python/plugins/processing/algs/qgis/ui. There is some discussion to make custom and dynamic dialogs easier in QGIS 3.0 so hopefully this will be easier in the future.

The quick (and probably ugly looking) way would be to hardcode a couple of variables and hide them in the advanced parameters. Probably it would be something like:

```
*ParameterString|variables>variable>name|Variable 1 name|None|False|True 
*ParameterBands|variables>variable>expr|Variable 1 expr|None|False|True
*ParameterString|variables>variable>name|Variable 2 name|None|False|True 
*ParameterBands|variables>variable>expr|Variable 2 expr|None|False|True
```

Similarly for aggregators, but you will have to list all aggregator options for all aggregators and mention in the description to which aggregator they are relevant:

```
ParameterSelection|aggregators>aggregator>type|Aggregator 1 type|MIN_MAX;AVG;PERCENTILE|0
ParameterBands|aggregators>aggregator>varname|Aggregator 1 source band|||
ParameterNumber|aggregators>aggregator>percentage|Aggregator 1 percentage (valid only for PERCENTILE aggregator)|0|100|50
ParameterNumber|aggregators>aggregator>weightCoeff|Aggregator 1 weight coefficient (valid only for AVG aggregator)|0.0|1.0|0.1
```

For the multiple source files it's probably best to use ParameterMultipleInput (https://github.com/DHI-GRAS/QGIS/blob/master/python/plugins/processing/core/parameters.py#L343). But you might need to modify GPFAlgorithm (https://github.com/DHI-GRAS/QGIS/blob/master/python/plugins/processing/core/parameters.py#L343 and https://github.com/DHI-GRAS/processing_gpf/blob/binning/GPFAlgorithm.py#L231) to match and print `<sourceProductPaths>` instead of `<ProductSet-Reader>`.

I will try to have a more detailed look next week.

**Comment by j08lue** [comment]
After a few bug fixes, all but one of the algorithms are tested to work:
1. CC L1P
2. CC L2R
3. CC L2W
4. FUB
5. MPH
6. OWT

I only tested them with default parameters but expect them to work with other settings, too. However, if not, please [report any errors as new issues](https://github.com/DHI-GRAS/processing_gpf/issues/new).

### ~~Question 1~~

~~The algorithms all output `GeoTIFF` files. However, these seem to lack additional information when you want to use them as input to other algorithms, e.g. when you generate a MERIS L1P product from a L1B product and save it as GeoTiff, you will not be able to use that as input to CC L2R or CC L2W. It seems to be lacking some meta information (e.g. sun zenith).~~

~~Do you need to chain one QGIS BEAM algorithm to another? In that case, we would need to add an option to output the product as `BEAM-DIMAP`. @radosuav, what do you think about this?~~

### Question 2

How important is the **Level-3 Binning** algorithm for the OP? I am happy to add it but it will take quite a lot of extra work, as discussed above.

**Comment by radosuav** [comment]
There is already an option to save as BEAM-DIMAP (at least on my installation) when you select the "Save to file" option:
![screenshot](https://cloud.githubusercontent.com/assets/4759850/18515994/a6ee390a-7a97-11e6-9a11-1c90eb5b5eb1.png)

The problem then is that DIMAP is not supported well by GDAL so those files can't be visualized in QGIS until the final output is saved as TIFF. Currently this is handled by mentioning this limitation in the relevant workflows and also in https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/README.md. Alternatively you could create BEAM only modeler, based on SNAP only modeler (https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/GPFModelerAlgorithm.py and https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/GPFModelerDialog.py) and then all the intermediate steps would be performed within the model. But I'm not sure if this is worth the effort since I hope that all the BEAM functionality will appear in S3TBX soon ;)

**Comment by j08lue** [comment]
Thanks @radosuav, my mistake. I did not see that `.dim` output was already an option and even [documented](https://github.com/DHI-GRAS/processing_gpf/blob/GW-A_dev/README.md).

**Comment by j08lue** [comment]
Here are the BEAM module files that I added: [BEAM_additions_gpf_issue12.zip](https://github.com/DHI-GRAS/processing_gpf/files/500050/BEAM_additions_gpf_issue12.zip)

You can install them by placing them in `C:\Program Files\beam-5.0\modules` and restarting BEAM.

**Comment by JanMil** [comment]
Hey guys, I added the BEAM modules to my BEAM install folder, but they won't show in my processing toolbox. Any ideas?

**Comment by j08lue** [comment]
@JanMil This could have different reasons. To start, please check whether they are correctly installed by accessing them in BEAM?

E.g. `BEAM > Processing > Thematic Water Processing > MERIS CoastColour Processors ... > ...` - just check that they exist.

**Comment by JanWev** [comment]
Sorry, I already erased my question as I realized were my mistake came from. I used an installation from the DHI FTP server and just added your BEAM_additions_gpf_issue12.zip modules instead of using the files from https://github.com/DHI-GRAS/processing_gpf/

But thanks for the fast response

**Comment by j08lue** [comment]
I moved the remaining algorithm to its own issue (#36).
