### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by pcav** [DHI-GRAS/processing_gpf#18]
Please see: https://lists.osgeo.org/pipermail/qgis-developer/2016-December/046237.html

**Comment by j08lue** [comment]
Thank you, @pcav, @radosuav and I were just discussing this:

From @radosuav:

> It looks like we will have to remove .class file from https://github.com/DHI-GRAS/processing_gpf/tree/GW-A_dev/processing_beam_java. See http://osgeo-org.1560.x6.nabble.com/Plugin-618-Processing-BEAM-and-SNAP-algorithm-Provider-approval-notification-td5300194.html and http://osgeo-org.1560.x6.nabble.com/Plugin-1102-AequilibraE-approval-notification-td5300322.html. 
> 
> It's not a big issue but it will mean that the users will have to either compile the Java code themselves or download the binary from GitHub. In case of full WOIS distribution the .class file can of course still be included in the plugin. 
> 
> We could add some code that would download the missing file from GitHub automatically (with user's permission of course) but I would like to keep it simple and just display a warning message when BEAM provider is activated and class file is missing and also maybe when the "Bands" button is clicked in BEAM algorithms (this is where the Java code is used). In SNAP this problem does not exist because Snappy interface is used instead. 
> 
> Let me know what you think. 

(hope it's OK I post this here)

**Comment by j08lue** [comment]
If I understand correctly, the need to remove the .class file is because QGIS maintainers (currently?) do not want compiled code distributed with plugins.

Let us not invest too much time into BEAM support, but use this issue as extra leverage to push Brockmann to merge all their algorithms into SNAP.

I would prefer a simple note to the user to download the file from GitHub, maybe showing the exact location where they should place the file. 

So not too much extra code in processing_gpf that we will need to remove e.g. when QGIS changes their policy (I see we are not the only ones with this issue).
