### ISSUE TITLE
Problem with BEAM Reproject Image

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/processing_gpf#22]
> BEAM Reproject image does not work with MERIS RR or FRS data (haven’t tested it with other data, so maybe it doesn’t work at all). The process will not start, instead the following message is returned *“Missing parameter value: The name of the elevation model for the orthorectification. If not given tie-point data is used”*

**Comment by j08lue** [comment]
We are unable to reproduce the error you get with BEAM Reproject image. 

Are you using an up-to-date version of processing_gpf? With SNAP 3, you should use v1.3.1 which was last changed on 14 October 2016. You can download it from https://github.com/DHI-GRAS/processing_gpf/releases/tag/v1.3.1. If you already updated to SNAP 5, please use the latest version https://github.com/DHI-GRAS/processing_gpf/archive/GW-A_dev.zip

If this is not the issue, could you send me a screendump of your parameters panel and the error message?

**Comment by radosuav** [comment]
The issue does exist but only when Processing from QGIS 2.18 is used. Everything works fine with Processing from QGIS 2.14 or ESA_Processing.

The problem is that by default ParameterString has "optional" variable set to False which stops the algorithm form executing when no value is provided (as is the case with elevationModelName in Reproject). It looks like in previous versions of Processing this wasn't enforced but in 2.18 is.

The fix is very easy and involves modifying the behavior in the algorithm description text files. I'll make a PR.
