### ISSUE TITLE
String Processing Parameter

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#31]
I see that the parameters are only stored in a graph, after they be used in an algorithm. This is the case for 'Raster layer' parameter, that needs to be used with Read Algorithm, and 'Extent' parameter, that is stored in the graph xml if linked with an algorithm, like 'Subset image'.

However, the 'String' parameter is not stored in the graph xml file, even if connected with an algorithm. For instance, I've tried to use it for let create the 'Expression' for 'BandMath' alg in a graph. If a 'default value' is defined in 'String parameter definition', that value is stored in the BandMaths, but the 'String' parameter doesn't show up in the graph user interface.

Can anyone confirm?

**Comment by radosuav** [comment]
This issue exists in BandMath for the same reason as #26: the expression parameter is nested inside <targetBands><targetBand> tag. The solution is simple and very similar to #29.

However, after this is fixed another problem is exposed. Since expression parameter is of ParameterBands type this type has to be added to the GPF modeler (i.e. #30). This appears simpler then I initially thought but there are still some things I need to figure out. I hope to have a PR this or next week.

**Comment by PedroVenancio** [comment]
Thank you very much @radosuav !
